export const GET_APPLICATIONS = 'GET_APPLICATIONS';
export const GET_ONE_APPLICATION = 'GET_ONE_APPLICATION';
export const ADD_APPLICATION = 'ADD_APPLICATION';
export const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
export const DELETE_APPLICATION = 'DELETE_APPLICATION';
